refactor(client): reset bank doors
Qbox-project/qbx_bankrobbery pull request #12
Opened 2024-01-02 01:45 UTC by MafewTM

## Description

- Refactors the resetBankDoors function into resetBankDoors and resetDoor functions
- Use cache.resource instead of `GetCurrentResourceName()`

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-01-02 07:06 UTC, Manason requested changes

2024-01-02 07:06 UTC, Manason commented on client/fleeca.lua
> +local function resetDoor(object, isBankOpen, closedHeading, openHeading)
Consider passing in the bank 'object' instead, which contains isBankOpen, closedHeading, and openHeading.

2024-01-03 06:38 UTC, Manason approved these changes

2024-01-03 15:01 UTC, solareon approved these changes

2024-01-03 15:01 UTC, merged